version: '3.8'

services:
    t4tech-api:
        image: danyllo431/laravel_octane_php83:latest
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - mysql
            - redis
        networks:
            - t4tech
    mysql:
        image: epionebr/mysql:tagname
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: t4tech
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - ./data/mysql/dbdata:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=4G
        networks:
            - t4tech
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9006:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=1G
        networks:
            - t4tech
    redis:
        image: redis
        networks:
            - t4tech

networks:
    t4tech:
        driver: bridge
